[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/node-service.Dockerfile"
watchPatterns = [
  "/package.json",
  "/package-lock.json",
  "/docker/node-service.Dockerfile",
  "/packages/shared/**",
  "/railway/pet-service.toml",
  "/services/pet-service/**",
  "/services/image-service/**",
  "/services/adoption-service/**"
]

[deploy]
startCommand = "node services/pet-service/src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
